### ISSUE TITLE
Attendee - Event Page - Get Tickets

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#102]
## Background
A user should be able to select a ticket type they want to purchase from the Event page. See [video](https://vimeo.com/290056954). 

## Scenario: A user selects get tickets on the Even page
- [ ] When I select get tickets
- [ ] Then I can select a ticket type
- [ ] And then I am directed to Checkout

**Comment by daybreaker** [comment]
Didnt get to this one, but I think we could use https://github.com/octopitus/rn-sliding-up-panel

**Comment by Mcscott142** [comment]
Switching out for #111 since Brad is on vacation and didn't get to this one. 111 can be worked solely by design.

**Comment by brittanygay** [comment]
Pulling this in to work on next

**Comment by brittanygay** [comment]
Styles are now complete for this screen. More info and screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/118

Putting this back into the backlog so @daybreaker and I can work on getting the scrolling section animation set up for this screen.

**Comment by daybreaker** [comment]
@brittanygay my `event-nav` branch also has Get Tickets in it. It also needs a design thing to fill in the extra space at the bottom.

**Comment by brittanygay** [comment]
@daybreaker I branched off of `event-nav` so the extra space bug should be fixed (I'm looking at it now and it looks right to me). Let me know if I misunderstood this!

**Comment by brittanygay** [comment]
Ohh gotcha @daybreaker! No I didn't see these updates yet, I'll pull it down and make those changes!

**Comment by brittanygay** [comment]
@daybreaker I just pushed up edits for the style bugs that we discussed. The gray area below the content is now adjusted, and I made a few other small tweaks, such as removing un-needed styles so the text aligns properly.

Passing this back up to you since it's on the `event-nav` branch. Once the other screens are complete we will be able to get this into review and get everything merged!

New screenshot:
<img width="364" alt="screen shot 2018-09-27 at 5 25 25 pm" src="https://user-images.githubusercontent.com/14582709/46178027-c6afaa80-c27a-11e8-969e-396136239751.png">
