### ISSUE TITLE
Catch All Design Tweaks ticket

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#144]
## Background
@mscscott142 to break this out more

From Zach Via Slack:
>There are a few things off, but some of which I can live with, I want to make sure we're paying extra close attention to this spacing/sizing:

>Status bar should be black on all white headers

>City should be “Philadelphia, PA”
- not all caps abbreviation

>Search area:
- icon not correct color or image
- alignment of icon and text incorrect
- should have rounded corners

>Margin between search and “Hot This Week” should be 45px

>Hot this week image should have a dark transparent gradient below the text at the bottom so it's readable

>Margin between featured image and Upcoming header should be reduced to 70px

>The event name and showtime and venue:
- Revisit font sizing
- Left align to the outside edge of the event image

<img width="1164" alt="ios_app__zach_-_dev_prep__sketch" src="https://user-images.githubusercontent.com/6877299/46614064-8651f700-cada-11e8-8db8-9eb70f6dc505.png">

>Date should be to the right vertically aligned to the top of the event name

>Top Line Info should be above the event name

>Padding at the top should be reduced
<img width="1505" alt="ios_app__zach_-_dev_prep__sketch 1" src="https://user-images.githubusercontent.com/6877299/46614110-9d90e480-cada-11e8-9642-c7667ef755b6.png">

>When you arrive at this view the scrollable area should auto rise up to the top to expose more of the summary form (55px from the bottom of the back arrow)
When the tickets are above 1, the minus button (-) should take an active state (pink)
<img width="1406" alt="ios_app__zach_-_dev_prep__sketch 2" src="https://user-images.githubusercontent.com/6877299/46614255-f8c2d700-cada-11e8-9fcc-b842458b5aff.png">

>The status bar should be black

>The header should not scroll up

>The tabs should be updated to match the spec’d version

>The cards should have rouded edges

>The cards should have a black gradient below the text so it’s readable

<img width="1639" alt="ios_app__zach_-_dev_prep__sketch 3" src="https://user-images.githubusercontent.com/6877299/46614286-109a5b00-cadb-11e8-9a25-ebb097a76405.png">

>This view should only scroll as much as is required to expose the nav items comfortably

![img_6146](https://user-images.githubusercontent.com/6877299/46614302-2019a400-cadb-11e8-81bc-cec2acf32e91.PNG)

**Comment by zmelamed** [comment]
@Mcscott142 @brittanygay I broke these down by priority "High Priority ASAP" are things that are making hard for me to get feedback from my team and are blocking me from getting it infront of test users because they're distractions and would like them prioritized immediately. If there is anything in the "Up Next unless quick fix" that can be knocked out in 15 mins, then also just knock those out, otherwise, though important, they can wait until a later if needed.

Explore View
- High Priority ASAP
  - Status Bar Should be Black
  - Search Area Styling
    - icon not correct color or image
    - alignment of icon and text incorrect
    - should have rounded corners
  - Black transparent gradient overlaying the featured event images so text is more readable
  - Fix region filter "Where are you looking for events?" styling
- Up Next unless quick fix
  - Region should not be all caps and should be full name “Philadelphia, PA”
  - The event name and showtime and venue:
    - Revisit font sizing
    - Left align to the outside edge of the event image
  - Margin between search and “Hot This Week” should be 45px
  - Margin between featured image and Upcoming header should be reduced to 70px

Event View Heading
- High Priority ASAP
  - Date should be to the right vertically aligned to the top of the event name 
- Up Next unless quick fix
  - Top Line Info should be above the event name
  - Padding at the top should be reduced

Ticket Wallet
- High Priority ASAP
  - The status bar should be black
  - The cards should have rouded edges
  - The cards should have a black gradient below the text so it’s readable
- Up Next unless quick fix
  - The header should not scroll up
- Later unless quick fix
  - The tabs and header should be updated to match the spec’d version

Purchase Summary/Completion View
- Up Next unless quick fix
  - When you arrive at this view the scrollable area should auto rise up to the top to expose more of the summary form (55px from the bottom of the back arrow)
  - When the tickets are above 1, the minus button (-) should take an active state (pink)
  - Increase size of (+) (-) buttons to 1.25x their current size (should end up at 50px)

Account View
- Later unless quick fix
  - This view should only scroll as much as is required to expose the nav items comfortably

**Comment by Mcscott142** [comment]
Breaking these out into issues now. Will organize `Next Up` using the last comment.

**Comment by Mcscott142** [comment]
Closing issue. These have been broken out into #153, #154, #156, #157, #158, #159
