### ISSUE TITLE
Designer - Application Layout - Status Bar

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#151]
## Background
We need to make the Status bar Black whenever there is a white background and vice versa. It should always be visible when navigating between pages in the application. 

## Scenario: 
- [ ] When I navigate through the Big Neon Application
- [ ] Then the Status Bar is visible on each page I visit

![46614064-8651f700-cada-11e8-8db8-9eb70f6dc505_png__2328x2282_](https://user-images.githubusercontent.com/6877299/46753956-d66dbc80-cc86-11e8-87e0-5304a62d01dc.png)

**Comment by brittanygay** [comment]
Putting this back down because I read through the docs and searched around and need some initial help setting this up. @CheetoMao may have to take over to help @daybreaker finish this up tomorrow.

**Comment by CheetoMao** [comment]
While working on this I've come across a few issues.

**User Generated Images & Event Images**
- we can't predict what color these images will be. A light image would make white text illegible, while a dark image would make black text hard to read.

**Problems with adding a background to the StatusBar:**
One solution is to bypass the unpredictable background images by adding a background color to the StatusBar component.

While this **does** fix the problem, adding a background color to the StatusBar feels a little 2008, also we would need to create a custom StatusBar for this since iOS doesn't support the 'backgroundColor' prop

Image Overlays?
Another way to get around not knowing the darkness/lightness of the background image would be to add a gradient overlay on top of those images.

The downside is that you are altering the image somewhat and as the user scrolls the gradient would stay with the picture, rendering the StatusBar content illegible at various points on the screen.
^ a note about this, it seems like most apps don't care too much about the StatusBar being legible as the user scrolls. 
ex: Netflix app has a StatusBar with white content, the StatusBar content is visible when you are at the top of the page, but as you scroll the StatusBar can be difficult to see depending on the page content.

**Other bugginess**
I added StatusBar components to most views with a defined `barStyle` prop, but it doesn't always stick. 
ex: clicking between Explore, Tickets, Account screens doesn't always display the correct barStyle

Suggestion: try to avoid the need for changing barStyle color on different views. If we go with the gradient overlay solution, we could use a white gradient so that the StatusBar content could stay black regardless of the screen.

**Comment by Mcscott142** [comment]
@zmelamed See last 2 comments from @CheetoMao. Starting here https://github.com/revelrylabs/bn-mobile-react/issues/151#issuecomment-429409393. Thoughts?

**Comment by Mcscott142** [comment]
@CheetoMao ^

**Comment by CheetoMao** [comment]
Just making a note that the status bar is currently set to `default` which is `dark-content` + transparent bkgd, so I think we can close out this ticket.

**Comment by Mcscott142** [comment]
👍 , closing.
