### ISSUE TITLE
Developer - My Tickets - Connect API

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#281]
## Background
We need to hook up the My Tickets piece for a user with tickets they have purchased. They will need to access them from here to be Scanned when attending an event. 

## Scenario: A user selects my tickets
Given I have purchased tickets either through the App or Big Neon Web
- [ ] When I select My tickets
- [ ] Then I see tickets to the actual events I have purchased
- [ ] And I can select them to view my QR code

**Comment by daybreaker** [comment]
Have the ticket index wired to the API and displaying everything properly. The API response was a bit weird, but I think I have it. 

Tomorrow need to get ticket show going. We have everything we need for that, though I may need to make some extra API calls to get the redeem_key for each ticket, since that data doesnt come back in the index response on the ticket objects. redeem_key is the only missing piece of data I need to be able to generate the QR Code.

**Comment by Mcscott142** [comment]
Created a ticket to resolve that, lets get this into Staging.

**Comment by Mcscott142** [comment]
@daybreaker Created a ticket to resolve that, let's get this into Staging. https://github.com/revelrylabs/bn-mobile-react/issues/311

**Comment by Mcscott142** [comment]
API pulls tickets to My Tickets, but not immediately. Created #325 and #311 to address. Moving to UAT.
