### ISSUE TITLE
If no ticket types are returned for an event, don't show pricing, and show unavailable message instead of ticket type selector

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#319]

**Comment by zmelamed** [comment]
![empty tix](https://user-images.githubusercontent.com/456953/49311803-0b340e00-f497-11e8-8bf2-e0b01edd1087.png)

**Comment by daybreaker** [comment]
Already hiding pricing, so I just need to use the existing hasTickets function to show that screen instead.

**Comment by jwietelmann** [comment]
I'm not sure that it should even be possible to get to this screen when there are no tickets available, but I have an idea that should not take me long to try. Will drop screenshots when I have something for Zach to look at.

**Comment by jwietelmann** [comment]
On second thought I'm just going to do the ticket as prescribed.

## What I was going to do

I was going to disable the purchase button and put "SOLD OUT" as the text so that you can't even get to this page.

## Why I'm not doing that

There is a lot of domain logic in called `getDetailPageButtonCta` that has rules for enabling/disabling the button and changing the text based on the `event.override_status`. These rules look intentional, and I don't understand their rhyme or reason enough to make that business decision right now. We can revisit the question of whether you should even be able to get to this page, but I'm going to go ahead and add the empty state.

**Comment by Mcscott142** [comment]
Does this screen exist? Tried creating some events with no ticket types and also just not on sale yet. I just don't have the option to purchase when the screen comes up.

**Comment by jwietelmann** [comment]
@Mcscott142 I unfortunately do not know the answer to that myself. To develop I cheated and temporarily forced purchasable tickets to show no available ticket types.

**Comment by Mcscott142** [comment]
I think this one needs design help plus Dev logic. cc @brittanygay. Note: We'll want to make sure this isn't an Externally ticketed event also, assuming those will not have Ticket Types.

**Comment by brittanygay** [comment]
@Mcscott142 I think I might need a dev to set this up first before I can do any design work on it, but I'm not sure what's already implemented because I can't see this state currently. @jwietelmann want to pair on this?
