### ISSUE TITLE
Event lists should be sorted by show start date/time

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#373]

**Comment by daybreaker** [comment]
Does the API have a sort field and sort order? Because doing it in the app could still cause events to show up out of order when pagination is introduced. If events are unordered by the API, page 2 could still bring up events that were supposed to show up first, but we wouldnt want to add them to the top of the list, because the user would have already scrolled past that part.

**Comment by jwietelmann** [comment]
Ideally, the API folk just make this into the default sort order. It probably takes equal work as having us do it, it's more correct, and then we don't have to go remove the hack from the mobile app once they do it (because you're right, they'll have to if pagination is going to ever work.)

That said, it's a cheap hack, and I don't have a problem doing it if this is the way to get it done right now.

**Comment by zmelamed** [comment]
There's a sort option you can pass the events.index request. @Krakaw can you drop an example of how to sort by show date?

**Comment by Krakaw** [comment]
There is a PR coming in soon that will let you sort on event_start / name
`server.events.index({sort: "event_start", dir:"asc/desc"})`

**Comment by jwietelmann** [comment]
I have a PR out for doing this, but in testing the API gives back a 400 error when adding these sort params. Marking this blocked until @Krakaw can confirm the sorting is shipped on the API side, and then I'll check out my PR branch and test it again.

**Comment by Mcscott142** [comment]
@Krakaw any update on below? 

>There is a PR coming in soon that will let you sort on event_start / name
server.events.index({sort: "event_start", dir:"asc/de

**Comment by jwietelmann** [comment]
Still getting 400 with request URL `https://beta.bigneon.com/api/events?sort=event_start&dir=asc` @Krakaw

**Comment by Krakaw** [comment]
We're having a little case issue with rust `https://beta.bigneon.com/api/events?sort=event_start&dir=Asc` will work
