### ISSUE TITLE
multiple ticket viewing scroll bar very slow - android

### ISSUE THREAD

**Issue by SWvheerden** [revelrylabs/bn-mobile-react#386]
There is a good second or two delay, before the scroll bar below the tickets update

**Comment by jwietelmann** [comment]
I haven't investigated this yet, but I want to flag this for whomever picks this up:

https://github.com/revelrylabs/bn-mobile-react/blob/develop/src/Tickets/showEventTickets.js#L120

We had a bug where the first ticket wouldn't show up until you wiggled it a little, and this workaround may have degraded the performance. If that's the case, I'm not sure what the fix is, but that's what I'd look at first in order to try and diagnose the problem. It seems like one of the more plausible explanations.
