### ISSUE TITLE
Attendee - Event Page - See Event Details

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#40]
## Background 
Latest Mocks are kept in the sketch file in this [folder](https://www.dropbox.com/sh/gt7c74ndhk7me5w/AADIxnNPe39Xbq3HJUCXfb9xa?dl=0). Please doublecheck that this screen has not changed before working ticket. Latest screens are in the production ready tab. 

## Scenario: A user clicks on an event from the homepage
- [x] When I am directed to the event show page
- [x] Then I see:
	- [x] An Event description
	- [x] Ticket Prices (starting from...)
	- [x] Youtube section
	- [x] Spotify Section
	- [x] Instagram Section
	- [x] Share button
	- [x] Favorite Button
	- [x] A way to close out the details
	- [x] Link to purcahse tickets

![ios_app_-_dev_version_sketch](https://user-images.githubusercontent.com/6877299/43804868-2f777f10-9a63-11e8-9fb2-4609459e8ea8.png)

**Comment by brittanygay** [comment]
Pulling this in to start working on

**Comment by brittanygay** [comment]
In review now, screenshots can be found here: https://github.com/revelrylabs/bn-mobile-react/pull/63

**Note for team:**
- I just used a placeholder img for the Spotify widget since that will be embedded later on
- I also went ahead and added placeholder arrows since we don't have any slideshows set up yet (like the homepage)

**Comment by brittanygay** [comment]
The stubbed out screen is now complete. Screenshots can be found here: https://github.com/revelrylabs/bn-mobile-react/pull/63

Note to @daybreaker:
There are two things that we still need to complete for this screen if you get time, both nav related :)
1. Need to make the close button functional (top left)
2. Replace bottom nav with Buy Ticket button (this screen only, if possible)

Putting this back into the backlog and assigning to @daybreaker for when he gets a chance to look at the above issues

**Comment by daybreaker** [comment]
Changing Event Show to a Modal with Get Tickets button stuck to the bottom of the screen.

**Comment by Mcscott142** [comment]
Need next build deployed on testflight for this i beleive. Blocking until then

**Comment by iamjoshfrank** [comment]
@brittanygay - a few questions:

1. There are two AC related to ticket prices (`- [ ] Ticket price` and `- [ ] The price of each ticket`). In the screenshot and in the app, I see "Tickets from $n". I assume this is duplicate criteria. Can you confirm?
2. At least on Android, there is some sort of weird artifact on the cover image at the top of the page (looks like maybe the bottom of the "play" circle from an image clipped from YouTube, perhaps?). I'm not sure this warrants re-working, but wanted to call it out. See screenshot:

**Comment by brittanygay** [comment]
@iamjoshfrank regarding your questions:

1. After double-checking the mocks, it looks like the price criteria in the AC is a duplicate, so we can remove one.

2. The image clipped is indeed the play icon. This isn't happening on any iOS devices from what I've tested, but this might take a minute to fix since I'll need help getting Android testing set up while I work this bug. I suggest we make a separate bug ticket for this, unless you think we should pull this ticket back instead.

Let me know what approach you would like to take for #2. Thanks!

**Comment by iamjoshfrank** [comment]
I'll split it out to a bug ticket.

**Comment by zekewell** [comment]
This passes on iphone.

**Comment by iamjoshfrank** [comment]
Closing. Opened #82 to address the circle artifact on Android.
