### ISSUE TITLE
Android - Back Button Exits the app instead of expected back behavior

### ISSUE THREAD

**Issue by Krakaw** [revelrylabs/bn-mobile-react#431]
Anytime the back button is pressed, the app exits instead of going to the previous navigation state.

**Comment by daybreaker** [comment]
Ohh, ok. It's possible this is because  in some places we're not providing the secondary navigate.goBack() that's needed. There's something about React Navigation that requires you to not only put the goBack in the onPress, but also handle it somewhere else too. I dont remember the exact details because its been a few months since I looked at it.

**Comment by Mcscott142** [comment]
I can re-produce this via production App. The hardware back button seems to work fine when using Expo (on develop branch). @daybreaker

**Comment by jwietelmann** [comment]
There's a section about this in the react-navigation docs, but their docs site is dying at the moment. Dropping link here for when it's back up: https://reactnavigation.org/docs/en/custom-android-back-button-handling.html

**Comment by jwietelmann** [comment]
It seems there may be an ExpoKit bug: https://github.com/expo/expo/issues/1786

**Comment by jwietelmann** [comment]
We may have to do a temporary workaround where we completely disable the hardware back button. :/

**Comment by jwietelmann** [comment]
Brad just told me that react-navigation did a major release update, and we should check to see if this problem is fixed in that case.
