### ISSUE TITLE
Unable to check in via Guest List

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#485]
I'm unable to check in a guest manually. This is possibly due to the fact that the event hasn't started but the error message needs to convey that if it's the case. 

![image from ios 4](https://user-images.githubusercontent.com/6877299/52079651-add24100-255b-11e9-9adc-679209e31159.png)

**Comment by jwietelmann** [comment]
this is that whole thing where the `redeem_key` is null - i thought they were going to change that?

**Comment by zmelamed** [comment]
needs to be after the doortime to be able to redeem

**Comment by jwietelmann** [comment]
@zmelamed Are you going to change this soon? I'm worried about it. If I'm early for a show and lining up to get in when the doors open, I'm pulling up my tickets before the doors actually open... So then when I get to the door person, my QR isn't going to scan until I close and re-open the tickets list. Imagine that times X people.

**Comment by zmelamed** [comment]
Yeah that's a fair point. I think for the short term we can return the redeem_key at least the day of show until we design a reasonable solution to make this work. @Krakaw what are your thoughts?

**Comment by Krakaw** [comment]
I think that will work, we can default the door time to the start of the day of the event when the event is created. This should solve the issue for now. 
Because Big Neon is a digital first ticketing system, we have a security vs convenience debate here where we don't want people being able to subvert the system because they can print and scalp tickets / try duplicate active QR codes etc. Maybe if there is no redeem_key we display a notice to the user that the doorman can scan their ticket and view their details but they must refresh the QR at '2019-02-01 22:00' (when the doors open). Or, we could easily see that there's no redeem_key and create a setTimeout to refresh it for them for when the doors actually open considering they are already in the queue waiting with their tickets open it must be very soon, but that is something we can create a new issue for.

**Comment by zmelamed** [comment]
@krakaw we can’t modify the actual door time because it’s displayed on the client side and will be set by most venues regardless of what we default it to. 

For now I think we may want to consider returning the redeem key based on it being the same day as the door time to avoid issues in the very short term and so we can capture some data to help us fully spec out a wholistic solution that doesn’t interfere with common behavior

**Comment by Mcscott142** [comment]
Closing based on https://github.com/big-neon/bn-api/issues/960
