### ISSUE TITLE
Attendee - My Tickets - Message for when QR code not present on Upcoming Event

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#498]
## Background 
When I purchase a ticket via the App and I'm re-directed to `My Tickets`, then selecting a ticket just shows the bn logo in place of where the QR code should be. After a few minutes when re-entering `My Tickets` and selecting a ticket the QR then appears. 

If it takes a few minutes for a QR code to be generated, we should provide a message to the user in the empty QR code space, letting them know their tickets are being prepared. 

## Scenario: A user purchases a ticket
Given I have purchased tickets and I am directed to `My Tickets`
- [ ] When I select my recently purchased ticket
- [ ] And the QR code is not present
- [ ] Then I am informed that my Ticket will be available shortly in the empty QR code space

**Comment by zmelamed** [comment]
It should be immediately available, so that's something that needs to be looked at as a bug, we've had issues before with openning tickets from the wallet immediately after purchase so I wonder if it's related. Either way as it stands I don't think this is a scenario where we want to improve the UI in that case, but rather ensure the QR code gets generated on first load reliably

**Comment by Mcscott142** [comment]
👍 , I'll close this.
