### ISSUE TITLE
Doorperson - Should see the last successful scan check-in info overlaying the scanner view after the scan

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#507]
After a successful scan, a pill shaped card should appear overlaying the scanner view showing the persons name, and ticket type
![image](https://user-images.githubusercontent.com/456953/52739500-ee7f8080-2f85-11e9-90d2-936f0738cb61.png)

**Comment by jwietelmann** [comment]
Grabbing this. I think we even have the design code already available in our git history. It's a matter of finding it and then wiring it up to actual data.

**Comment by jwietelmann** [comment]
Explanation of changes I made...

* Added the info pill
* Made an executive decision to kill the green checkmark icon for now because:
  * Its meaning and behavior are not clear
  * We don't have an answer for what it would look like in manual mode after the ticket was scanned but before it's redeemed
  * If we try to put more meaning into it, it seems redundant to the overlay message icons
* In manual mode, removed user/ticket info from the bottom tab because it's redundant to the pill until we do more with that tab.
* The pill stays on the screen until the next ticket is scanned.
* The overlay messages continue to display for X seconds and then go away to resume scanning.
