### ISSUE TITLE
Guest List - Scroll up vertically when opening

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#517]
## Background
Currently, it feels a little disjointed when navigating to the guest list in the app. The screen transition is a little off from what we want (horizontal scroll instead of vertical) and the app navigation shows up.

This ticket is for the guest list transition to move up vertically on the screen.

TODO: Link to Vimeo

## Scenario: A doorperson navigates to the guest list
- [ ] When I select the guest list on an event
- [ ] Then the screen transition happens vertically
- [ ] And it appears that the guest list is covering the Scanner screen

**Comment by daybreaker** [comment]
Trying to get this to work: https://github.com/octopitus/rn-sliding-up-panel

Having issues even getting something to display, to even start working on the slide up. Might put it down and switch to the more important tickets

**Comment by daybreaker** [comment]
Actually, this looks more promising: https://www.npmjs.com/package/rn-bottom-drawer

Might give this one a shot tomorrow.

**Comment by daybreaker** [comment]
I'm wondering if it might be better to turn this into a button that just maintains the current navigation, instead of making a pull up panel.

One issue with the pull up panel would be knowing when to turn off the QR scanner camera. 

Another issue is we're not gaining a ton with a pull up panel outside of a stylistic thing, which for a doorscanner isnt a priority.

**Comment by Mcscott142** [comment]
@daybreaker you can punt on this and move to #523 or #522. I agree that functionality and ease of use is the path to take here.

**Comment by brittanygay** [comment]
Pulling this in to work on
