### ISSUE TITLE
Developer - TestFlight/Fastlane - Stand Up Testflight + Fastlane

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#58]
## Background
We need to get TestFlight and Fastlane stood up so we can QA/UAT 

- [ ] Set Up TestFlight
- [ ] Set up Fastlane

**Comment by Mcscott142** [comment]
Any updates on this one?

**Comment by daybreaker** [comment]
There's a deploy script that pushes ios to Test Flight, and android to the alpha channel on Google Play.

Google Play is under my account right now, since they dont have "Teams" like the App Store does. We'll need to switch that to a Revelry or Big Neon account in the future.

Currently waiting for the `git push` to go through. It's taking a super long time for some reason.

**Comment by Mcscott142** [comment]
@daybreaker how do we get set up? Do I need an invite to something?

**Comment by iamjoshfrank** [comment]
Closing this out since I've seen new builds going out this week via TestFlight and Google Play.
