### ISSUE TITLE
Doorperson - Event - Download Guest List

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#593]
## Background 
In the event of Network or Blind Spot problems for a venue, we should consider some solutions for guest entry. 

We could offer the ability to download a guest list for an event when there is little or no connectivity. Like Spotify will allow you to download a playlist for offline mode. 

The biggest issue there would be the verification of tickets. Per @jwietelmann in slack 
> we wouldn't be able to verify tickets

> we could only say, like "as far as i know this hasn't been redeemed yet. also it may or may not actually be for this event."

>if the door people aren't networked, there's no way for person A to know that person B already scanned this ticket

>the main disadvantage. you just can't figure out if people are cheating with shared tickets until after the network is back

This could be more of a stopgap solution for a Network going down.

## Scenario: A doorperson downloads the guest list
- [ ] When I select download guest list
- [ ] Then I can scan a ticket or complete a check sans a Network connection

**Comment by Mcscott142** [comment]
@zmelamed Just want to get your eyes on this and thoughts around a solution for scanning in poor connection scenarios.

**Comment by jwietelmann** [comment]
Just thought of an additional disadvantage: We would have to rebuild fuzzy guest list search locally within the app.

Also a question: Are paged API responses actually being served by the API now? We sort of skirt around that with the search right now because if you search narrowly enough, it doesn't end up mattering. If we need to get the entire list and store it locally, it matters a great deal.
