### ISSUE TITLE
My Tickets - Transfers Section

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#610]
## Background
It doesn't look like we are placing Transferred tickets in the Transfer tab of `My Tickets`

## Scenario: A user transfers tickets
- [ ] When I Transfer a ticket
- [ ] Then I see that ticket in my `Transfers` tab in `My Tickets`

**Comment by jwietelmann** [comment]
Rejected during poker. The request is ambiguous because there are pending transfers and completed transfers. It's never been clear what tickets are supposed to show up in the transfers tab, and it's never been clear what kind of display/behavior they should have. Presumably, something different than tickets you're still using, but I don't think that's ever been dealt with really.

We would really benefit from a more comprehensive description of the transfers feature from end to end. It's been kind of a confusing piecemeal mess, and I want to stop that.

**Comment by Mcscott142** [comment]
@zmelamed Has the transfer flow been spec'd out yet?
