### ISSUE TITLE
Performance - Improved logic for event image loading/caching

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#661]
- [ ] Event images should only ever be downloaded once (first download)
- [ ] Event images should not be re-downloaded every time the event update request is made, only when the images are changed
- [ ] When the event is no longer listed/has ended, the event images that are cached should be removed from the cache (auto expiry could be set to the event end date/time) to respect the users local storage
- [ ] If the event exists in the users ticket wallet it should persist locally

Is there any kind of lazy loading/pagination happening on the list view?

**Comment by daybreaker** [comment]
Supposedly for ios, if the API server sends back the image with a Cache-Control header, it will automatically cache that image. Not sure about Android, but as of last year, I dont think it was doing it.

I'm wondering if this might be the best option though, because there are no real ImageCache libraries out there that arent just a standard "cache everything until the OS wipes the cache", and building a custom Image Cacher could take a while.

As for pagination, we arent doing any of that yet. Right now, the API sends back: `paging: {page: 0, limit: 100, sort: "event_start", dir: "Asc", total: 27, tags: {}}`

I'm guessing we can set limit in our API request to be something like 20? And then start paging. I would spin up a new ticket for paging events.

**Comment by Mcscott142** [comment]
@bryanjos @daybreaker y'all want to talk about this and recommend a solution?

**Comment by bryanjos** [comment]
I'm going to make it work using the built-in react native stuff, meaning iOS only

**Comment by daybreaker** [comment]
It should already though, right? Isnt it based on the API returning cache-control value in the header response?

**Comment by bryanjos** [comment]
This is still a work in engineering. Be back when I have something to show

**Comment by bryanjos** [comment]
I got a thing working but also it doesn't cover all bases.

If the urls for the images all had file extensions it would be more robust. But without, there is a "chicken or the egg" situation where you need to know the content type before you can add an extension and making the file path.

**Comment by bryanjos** [comment]
Add react-native-expo-image-cache and using the for the event images. Looks stable enough and uses many of the same techniques I was in my own implemented version.

**Comment by bryanjos** [comment]
> When the event is no longer listed/has ended, the event images that are cached should be removed from the cache (auto expiry could be set to the event end date/time) to respect the users local storage

So this one is probably harder to implement than worth the effort. The operating systems will usually delete cached app data on their own when space is needed as well. Cache data being different than things like document and photo data

**Comment by bryanjos** [comment]
This seems good on Android as far as I can tell
