### ISSUE TITLE
Product Exploration - Self-Discovery

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/bn-mobile-react#765]
An Issue to capture discoveries as we explore the current state of the application from the POV of the end users (Attendees and Door Scanners) and surface opportunities for improvements and new features.

**Comment by iamjoshfrank** [comment]
@bryanjos @jpatricknola @CheetoMao - putting this straight to `In Progress` and in a rare move, I'm co-assigning all 4 of us.

**Comment by bryanjos** [comment]
Would like to have the app's version somewhere in the UI. Why? Because it receives over-the-air (OTA) updates so the version shown in the App Store may not match the one users have

**Comment by bryanjos** [comment]
Doorperson: Make guest list screen available from the event screen. This way the doorperson does not have to go through 2 extra screens and clicks and get to the list

**Comment by jpatricknola** [comment]
So far the most glaring pain point apparent from app reviews is that some people are mad about having to download the mobile app to get into the concert for which they bought tickets.   The Big Neon FAQ page addresses this issue:

Q: But wait, I don't have the app - can I still get into the show?
A: No app? No problem! The app helps eliminate counterfeit tickets, and will enable more cool features at shows in the near future. If you don't want to use it you can always check in at the door. Just be sure to bring your photo ID.

User feedback (in the form of app store reviews) shows that some people are either unaware that they can gain access to the show without downloading the app, or in some cases, believed they would be able to do so but found they were actually unable to gain access to the show without downloading the app.   

Given that email address is required for any purchase of tickets, a potential solution is to just email QR codes upon purchase of tickets.   This would make it so that people who don't want to download the mobile app will still have a QR code ticket for the door person to scan.

**Comment by bryanjos** [comment]
Attendee - My Tickets - Show non-changing information about a ticket twice.

Why? The information stays the same. There is a bug caused by loading a huge gif multiple times. We can still carousel the dynamic info

**Comment by bryanjos** [comment]
I checked in on the web side of things as an attendee. You can do more things inside the mobile than on the web. Nothing really gained there.

**Comment by bryanjos** [comment]
There were issues to have some of the available for each event at https://beta.bigneon.com/admin/events in the mobile app for doorpeople but I don't think the apis or data were ever made available

**Comment by CheetoMao** [comment]
HMW denote events that require the user to purchase tickets through eventbrite or another app/website without deterring them from using the app?

**Comment by iamjoshfrank** [comment]
re: https://github.com/revelrylabs/bn-mobile-react/issues/765#issuecomment-491919119 from @jpatricknola 

Resorting to QR codes via email is more of a business call than I'm comfortable making here. How does this help maintain the verifiability of a ticket? Does the blockchain-enabled portion of the ticketing rely on keeping things tied to a device / mobile app? What if a QR-coded email is forwarded or printed and distributed to multiple "buyers," initiating a scam?

I like the way you're thinking through the stated user problems, Patrick. Let's pin this for discussion with @zmelamed .

**Comment by iamjoshfrank** [comment]
> There were issues to have some of the available for each event at https://beta.bigneon.com/admin/events in the mobile app for doorpeople but I don't think the apis or data were ever made available

@bryanjos - i think you're missing a few words around ..."to have some of the [blank] available for each event..." so your comment doesn't help me know what to do next, though I trust it's a good idea to look into whatever you were suggesting.

**Comment by iamjoshfrank** [comment]
> HMW denote events that require the user to purchase tickets through eventbrite or another app/website without deterring them from using the app?

Is this a thing? There are events listed on Big Neon that require purchase via an outside platform??

**Comment by iamjoshfrank** [comment]
Closing, have captured most of these items in separate Issues.
